### ISSUE TITLE
Goocle Cloud Credentials on plan command does not work 

### ISSUE THREAD

**Issue by supergrilo** [CircleCI-Public/terraform-orb#64] opened 2022-04-20 21:05 UTC
Hi all! 

The command plan does not recognize google credential variable.
A set this variable in a context, but auth does not work

``` version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: >-
            rm -rf ~/.gitconfig
          name: clean gitconfg
      - run:
          command: >-
            git config --global url.https://oauth2:$TERRAFORM_GITHUB_TOKEN@github.com.insteadOf https://github.com
          name: Github Auth webeta
      - persist_to_workspace:
          root: .
          paths:
            - ""
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          path: .
      - terraform/plan:
          path: .
          var: GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context: gcp-insane-wizard
```

any one know how to do this?

**Comment by KyleTryon** [comment] 2022-05-19 13:56
Hello,

This appears to be a duplicate of #51. The issue has been resolved and will be released shortly. Please follow #51 for the update (likely later today).

**Closed as completed by KyleTryon** 2022-05-19 13:56 UTC
Labels: awaiting release
