### ISSUE TITLE
Terraform init with S3 backend is failing with terraform version 0.15+ and orb 3.0.0

### ISSUE THREAD

**Issue by markandersontrocme** [CircleCI-Public/terraform-orb#50] opened 2021-08-31 20:44 UTC
**Orb Version**
The version number of the orb
3.0.0

**Describe the bug**

When `terraform/init` job is ran with `backend_config`, we get an error: `Error refreshing state: InvalidBucketName: The specified bucket is not valid.` 
**To Reproduce**
Run a terraform init using aws s3 as backend_config

**Expected behavior**
Terraform to init properly with an s3 backend

**Additional context**
If we use terraform version 0.14.x with orb 2.x.x we do not get this error, only with version 0.15.x + and orb 3.0.0

**Comment by mpraveenreddie** [comment] 2021-09-01 13:25
@punkdata @KyleTryon @bendrucker

**Comment by markandersontrocme** [comment] 2021-09-01 13:30
Seems to be the same error as: https://github.com/CircleCI-Public/terraform-orb/issues/51

**Comment by KyleTryon** [comment] 2022-05-19 13:54
Closing as duplicate of #51. For anyone following this issue, it has been resolved and is awaiting release. We will have an update coming out very shortly (likely today).

**Closed as completed by KyleTryon** 2022-05-19 13:54 UTC
Labels: bug
